### ISSUE TITLE
UTILIZAR RAMAS PERSONALES.

### ISSUE THREAD

**Issue by ghost** [juagarciaco/EQ-Calculator#1]
Buenas noches,

Cree una rama para cada uno de nosotros donde nos encargaremos de subir nuestros aportes, la rama master la dejaremos libre para hacer en esta el posterior resultado del trabajo.

Cordialmente,

Daniel Felipe Montenegro

**Comment by juagarciaco** [comment]
Julian nos dijo hoy que siguiéramos todo en master para no complicarnos, y que no hay problema porque Git se encarga de unir lo que cada uno hace y si hay conflictos manda notificación.
